import { IconArrowUpRight, IconBrandInstagram, IconCheck, IconClock, IconDental, IconMapPin, IconMenu2, IconPhone, IconShieldCheck, IconSparkles, IconStar } from "@tabler/icons-react";
import MotionEffects from "./motion-effects";

export default function Home() {
  return (
    <main>
      <MotionEffects />
      <div className="announcement"><span className="announcement-dot" /> SITE DEMONSTRATIVO — dados, depoimentos e contatos são fictícios; não use para agendamento.</div>
      <header className="site-header">
        <a className="brand" href="#inicio" aria-label="Clara Odontologia — início"><span className="brand-mark"><IconDental size={25} stroke={1.7} /></span><span>clara<span className="brand-dot">.</span><small>ODONTOLOGIA INTEGRADA</small></span></a>
        <nav className="desktop-nav" aria-label="Navegação principal"><a href="#sobre">A clínica</a><a href="#tratamentos">Tratamentos</a><a href="#diferenciais">Por que a Clara</a><a href="#depoimentos">Depoimentos</a></nav>
        <a className="header-cta" href="#contato">Agendar consulta <IconArrowUpRight size={16} /></a>
        <details className="mobile-menu"><summary aria-label="Abrir menu"><IconMenu2 size={22} /></summary><nav aria-label="Navegação móvel"><a href="#sobre">A clínica</a><a href="#tratamentos">Tratamentos</a><a href="#diferenciais">Por que a Clara</a><a href="#depoimentos">Depoimentos</a><a href="#contato">Agendar consulta</a></nav></details>
      </header>

      <section className="hero" id="inicio">
        <div className="hero-copy"><div className="eyebrow"><span /> CUIDADO QUE TRANSFORMA</div><h1>Seu sorriso,<br />do seu <em>jeito.</em></h1><p className="hero-lede">Odontologia acolhedora, tecnologia de ponta e um plano feito para você se sentir bem — em cada etapa.</p><div className="hero-actions"><a className="button button-dark" href="#contato">Quero cuidar do meu sorriso <IconArrowUpRight size={17} /></a><a className="text-link" href="#tratamentos">Conheça a clínica <span>↓</span></a></div><div className="hero-proof"><div className="proof-avatars"><span>MA</span><span>JL</span><span>RC</span><span>+</span></div><div><div className="stars"><IconStar size={13} fill="currentColor" /><IconStar size={13} fill="currentColor" /><IconStar size={13} fill="currentColor" /><IconStar size={13} fill="currentColor" /><IconStar size={13} fill="currentColor" /></div><p><strong>4,9/5</strong> de satisfação dos pacientes</p></div></div></div>
        <div className="hero-visual"><div className="hero-image" role="img" aria-label="Paciente sorrindo em um ambiente claro e acolhedor" /><div className="image-note"><span className="note-icon"><IconSparkles size={18} /></span><span><strong>Seu cuidado, sem pressa.</strong><small>Atendimento humano de verdade</small></span></div><div className="hero-tag"><span>+</span><strong>12 anos</strong><small>cuidando de sorrisos</small></div><div className="hero-image-caption">UM ESPAÇO PARA VOCÊ SE SENTIR BEM</div></div>
      </section>
      <div className="trust-strip"><span><IconShieldCheck size={19} /> Atendimento personalizado</span><i /><span><IconSparkles size={18} /> Tecnologia de ponta</span><i /><span><IconClock size={18} /> Horários flexíveis</span><i /><span><IconCheck size={18} /> Primeira avaliação acolhedora</span></div>

      <section className="intro section-wrap" id="sobre"><div className="section-kicker" data-reveal>BEM-VINDA À CLARA <span>01 — 03</span></div><div className="intro-grid"><h2 data-reveal>Um sorriso bonito<br />começa com <em>confiança.</em></h2><div data-reveal><p>A gente acredita que ir ao dentista pode ser leve. Por isso, aqui você é ouvido, entende cada escolha e participa do seu tratamento do começo ao fim.</p><a className="underlined-link" href="#diferenciais">Conheça nosso jeito de cuidar <IconArrowUpRight size={16} /></a></div></div><div className="intro-bottom" data-reveal><span>FEITO COM CALMA. PENSADO EM VOCÊ.</span><div className="line-art"><span /><span /><span /></div><span>ODONTOLOGIA COM PRESENÇA</span></div></section>

      <section className="treatments" id="tratamentos"><div className="section-wrap"><div className="treatment-heading"><div data-reveal><div className="section-kicker light">CUIDADO COMPLETO <span>02 — 03</span></div><h2>Seu sorriso merece<br /><em>atenção por inteiro.</em></h2></div><p data-reveal>Do cuidado preventivo à transformação que você sempre quis. Vamos encontrar juntos o melhor caminho.</p></div><div className="treatment-grid">
        {[{n:"01",title:"Clínica geral",desc:"Prevenção, limpeza e cuidado contínuo para a saúde do seu sorriso.",icon:"✳"},{n:"02",title:"Alinhadores",desc:"Alinhe os dentes com discrição, conforto e um plano sob medida.",icon:"⌁"},{n:"03",title:"Estética dental",desc:"Lentes, clareamento e restaurações com resultado natural e harmônico.",icon:"◌"},{n:"04",title:"Implantes",desc:"Recupere função e confiança com planejamento cuidadoso e seguro.",icon:"⌑"}].map((item)=><a data-reveal className="treatment-card" href="#contato" key={item.n}><div className="treatment-card-top"><span>{item.n}</span><span className="treatment-icon">{item.icon}</span></div><h3>{item.title}</h3><p>{item.desc}</p><div className="card-arrow"><IconArrowUpRight size={17} /></div></a>)}
      </div><div className="treatment-foot"><span>Não sabe por onde começar?</span><a href="#contato">Converse com a gente <IconArrowUpRight size={15} /></a></div></div></section>

      <section className="care section-wrap" id="diferenciais"><div className="care-image" data-reveal role="img" aria-label="Dentista conversa com paciente durante atendimento"><div className="care-image-label">A GENTE CUIDA DE PESSOAS,<br />NÃO SÓ DE DENTES.</div></div><div className="care-copy"><div className="section-kicker" data-reveal>O JEITO CLARA DE CUIDAR <span>03 — 03</span></div><h2 data-reveal>Você no centro.<br /><em>Sempre.</em></h2><p className="care-lede" data-reveal>Seu tempo, suas dúvidas e seu conforto importam. Aqui, cada plano começa com uma conversa — e só segue quando você se sente seguro.</p><div className="care-points"><div data-reveal><span><IconCheck size={16}/></span><p><strong>Escuta sem julgamento</strong><small>Conte o que te preocupa. A gente está aqui para ouvir.</small></p></div><div data-reveal><span><IconCheck size={16}/></span><p><strong>Tudo explicado, sem pressa</strong><small>Você entende as opções e decide com tranquilidade.</small></p></div><div data-reveal><span><IconCheck size={16}/></span><p><strong>Plano feito para sua vida</strong><small>Tratamento realista, pensado junto com você.</small></p></div></div><a className="button button-dark" href="#contato">Vamos conversar <IconArrowUpRight size={17} /></a></div></section>

      <section className="testimonial" id="depoimentos"><span className="quote-mark" data-reveal>“</span><p data-reveal>Eu tinha medo de dentista desde criança. Na Clara, pela primeira vez, me senti no controle e verdadeiramente cuidada.</p><div className="quote-author" data-reveal><span className="author-avatar">AM</span><span><strong>Ana M.</strong><small>Paciente Clara desde 2022</small></span><span className="quote-stars">★★★★★</span></div><div className="quote-index">01 <span /> 03</div></section>

      <section className="contact" id="contato"><div className="contact-inner"><div data-reveal><div className="eyebrow"><span /> SEU PRÓXIMO PASSO</div><h2>Que tal começar<br />com uma <em>conversa?</em></h2><p>Sem pressão, sem compromisso. Só um primeiro passo para cuidar de você.</p><a className="button button-light" href="https://wa.me/5511999999999?text=Ol%C3%A1%2C%20gostaria%20de%20agendar%20uma%20avalia%C3%A7%C3%A3o" target="_blank" rel="noreferrer">Agendar pelo WhatsApp <IconArrowUpRight size={17} /></a></div><div className="contact-details" data-reveal><div><IconMapPin size={18}/><p><strong>Onde estamos</strong><span>Rua Harmonia, 520 · Vila Madalena<br />São Paulo, SP</span></p></div><div><IconClock size={18}/><p><strong>Quando atendemos</strong><span>Seg–Sex, 8h às 19h<br />Sábados, 8h às 13h</span></p></div><div><IconPhone size={18}/><p><strong>Fale com a gente</strong><span>(11) 99999-9999</span></p></div></div></div></section>

      <footer className="footer"><a className="brand footer-brand" href="#inicio"><span className="brand-mark"><IconDental size={23} stroke={1.7} /></span><span>clara<span className="brand-dot">.</span><small>ODONTOLOGIA INTEGRADA</small></span></a><span className="footer-note">Cuidar do seu sorriso é cuidar de você.</span><div className="footer-social"><a href="https://instagram.com" aria-label="Instagram da Clara"><IconBrandInstagram size={18}/></a><a href="tel:+5511999999999" aria-label="Ligar para a Clara"><IconPhone size={18}/></a></div><div className="footer-bottom"><span>© 2025 Clara Odontologia Integrada</span><span>RT: Dra. Clara Mendes · CRO-SP 123456</span><a href="#inicio">Voltar ao topo ↑</a></div></footer>
    </main>
  );
}
